feedhabit:
  build: .
  ports:
    - "8088:8080"
  volumes:
    - ./build/feedhabit/gradle:/root/.gradle
modeshape:
  build: .
  dockerfile: Dockerfile.modeshape
  ports:
    - "9999:9990"
    - "8081:8080"
    - "8444:8443"

